try {
	// execute something
	const result =  addNum();
	console.log(result)
}catch (error) {
	// code to handle the error occurred during execution
	console.log(`Error ==> ${error.message}`)
}